/** بائعة الأحلام — خادم Express + Firebase Firestore */
const path=require('path'),crypto=require('crypto'),express=require('express');const {initializeApp,cert}=require('firebase-admin/app');const {getFirestore}=require('firebase-admin/firestore');
if(process.env.FIREBASE_CONFIG){try{initializeApp({credential:cert(JSON.parse(process.env.FIREBASE_CONFIG))})}catch(e){console.error('FIREBASE_CONFIG غير صالح',e.message);initializeApp()}}else{try{initializeApp({credential:cert(require('/etc/secrets/firebase-key.json'))})}catch(e){initializeApp()}}
const db=getFirestore(),ROOT=__dirname,PORT=process.env.PORT||3000,ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'admin123';
const DEFAULT_CONTENT={site:{name:'بائعة الأحلام',tagline:'كلمات تُكتب لتبقى… وأحلام تُروى لتولد من جديد.'},hero:{quote:{text:'هنا يسكن الحلم… وبين السطور تولد كلماتٌ لا تموت.',font:'Amiri',fontSize:26,color:'#8B1A1A',lineHeight:2},imageUrl:''},dailyExcerpt:{text:'مقتطف اليوم…',font:'Scheherazade New',fontSize:22,color:'#5C4033',lineHeight:2},book:{title:'كتاب بائعة الأحلام',blurb:{text:'نبذة مختصرة عن الكتاب…',font:'Tajawal',fontSize:18,color:'#3E3A39',lineHeight:1.9},defaultStyle:{font:'Amiri',fontSize:20,color:'#33302E',headingFont:'Aref Ruqaa',headingSize:28,headingColor:'#8B1A1A',lineHeight:2.1},chapters:[]},poems:[],excerpts:[],about:{text:'',font:'Tajawal',fontSize:18,color:'#3E3A39',lineHeight:2},social:{youtube:'',instagram:'',facebook:'',tiktok:''},theme:{primaryColor:'#8B1A1A',goldColor:'#C9A227',textColor:'#3E3A39',bgColor:'#FAF3E8',cardColor:'#FFFDF8',baseFont:'Tajawal',headingFont:'Aref Ruqaa',baseSize:17,headingSize:32}};
function mergeContent(c){c=Object.assign({},DEFAULT_CONTENT,c||{});c.book=Object.assign({},DEFAULT_CONTENT.book,c.book||{});c.book.chapters=(c.book.chapters||[]).map(x=>Object.assign({locked:false,blocks:[]},x));c.poems=(c.poems||[]).map(x=>Object.assign({locked:false},x));c.excerpts=c.excerpts||[];return c}
async function getContent(){let ref=db.collection('settings').doc('content'),snap=await ref.get();if(!snap.exists){await ref.set(DEFAULT_CONTENT);return DEFAULT_CONTENT}return mergeContent(snap.data())}async function saveContent(c){await db.collection('settings').doc('content').set(mergeContent(c))}async function messages(){let s=await db.collection('messages').orderBy('createdAt','desc').get();return s.docs.map(d=>({id:d.id,...d.data()}))}
const tokens=new Set(),attempts={};function token(){let t=crypto.randomBytes(32).toString('hex');tokens.add(t);return t}function getToken(req){let h=req.headers.authorization||'';if(h.startsWith('Bearer '))return h.slice(7);let c=(req.headers.cookie||'').split(';').find(x=>x.trim().startsWith('admin_token='));return c?decodeURIComponent(c.split('=').slice(1).join('=')) : ''}function admin(req,res,next){if(tokens.has(getToken(req)))return next();res.status(401).json({error:'غير مصرح'})}
const app=express();app.use(express.json({limit:'3mb'}));app.use(express.urlencoded({extended:true}));app.get('/',(_,r)=>r.sendFile(path.join(ROOT,'index.html')));app.get('/index.html',(_,r)=>r.sendFile(path.join(ROOT,'index.html')));app.get('/admin.html',(_,r)=>r.sendFile(path.join(ROOT,'admin.html')));
app.post('/api/login',(req,res)=>{let ip=req.ip||'unknown',now=Date.now(),a=attempts[ip]||{count:0,first:now};if(now-a.first>15*60e3)a={count:0,first:now};if(a.count>=10)return res.status(429).json({error:'محاولات كثيرة، حاول لاحقًا'});if(req.body.password!==ADMIN_PASSWORD){a.count++;attempts[ip]=a;return res.status(401).json({error:'كلمة المرور غير صحيحة'})}a.count=0;attempts[ip]=a;let t=token();res.setHeader('Set-Cookie',`admin_token=${encodeURIComponent(t)}; HttpOnly; Path=/; SameSite=Lax`);res.json({ok:true,token:t})});app.post('/api/logout',(req,res)=>{tokens.delete(getToken(req));res.setHeader('Set-Cookie','admin_token=; HttpOnly; Path=/; SameSite=Lax; Max-Age=0');res.json({ok:true})});app.get('/api/me',(req,res)=>res.json({authenticated:tokens.has(getToken(req))}));
app.get('/api/content',async(_,res)=>{try{res.json(await getContent())}catch(e){console.error(e);res.status(500).json({error:'خطأ في جلب المحتوى'})}});app.put('/api/content',admin,async(req,res)=>{if(!req.body||typeof req.body!=='object')return res.status(400).json({error:'بيانات غير صالحة'});try{await saveContent(req.body);res.json({ok:true})}catch(e){console.error(e);res.status(500).json({error:'خطأ في حفظ المحتوى'})}});
app.get('/api/messages',admin,async(_,res)=>{try{let m=await messages();res.json({messages:m,unread:m.filter(x=>!x.read).length})}catch(e){res.status(500).json({error:'خطأ في جلب الرسائل'})}});app.post('/api/messages',async(req,res)=>{let message=String(req.body?.message||'').trim();if(!message)return res.status(400).json({error:'يرجى كتابة الرسالة أولًا'});try{await db.collection('messages').add({name:String(req.body.name||'زائر مجهول').trim(),message,read:false,createdAt:new Date().toISOString()});res.json({ok:true})}catch(e){res.status(500).json({error:'خطأ في إرسال الرسالة'})}});app.patch('/api/messages/:id',admin,async(req,res)=>{try{await db.collection('messages').doc(req.params.id).update({read:true});res.json({ok:true})}catch(e){res.status(500).json({error:'خطأ'})}});app.delete('/api/messages/:id',admin,async(req,res)=>{try{await db.collection('messages').doc(req.params.id).delete();res.json({ok:true})}catch(e){res.status(500).json({error:'خطأ'})}});app.use('/api',(_,res)=>res.status(404).json({error:'المسار غير موجود'}));app.use((e,_,res,__)=>{console.error(e);res.status(500).json({error:'خطأ داخلي'})});app.listen(PORT,()=>console.log(`بائعة الأحلام تعمل على المنفذ ${PORT}`));
